#添加武器
weapon:
  #名字
  wooden_sword:
    #名字，必须
    name: 桃木剑
    #星级(1-5)，必须
    star: 1
    #伤害值，必须
    damage: 5
    #攻速
    attack_speed: 1.6
    #耐久
    durability: 50
    #攻击成功率加成(反闪避)
    success_attack_rate_add: 0
    #暴击率
    crit_rate: 0.05
    #暴击加成系数(0.5就是多50%伤害)
    crit_damage: 0.5
    #等级压制系数(可以是负数，等级低的玩家更容易胜利)高一级伤害多的系数
    level_repression: -0.01
    #等级压制上限
    level_repression_limit: 0
    #附魔属性(原版)
    enchant:
      unbreaking:
        1
        
  stone_sword:
    name: 石中剑
    star: 2
    damage: 5
    attack_speed: 2.2
    durability: 150
    success_attack_rate_add: 0.1
    crit_rate: 0.12
    crit_damage: 0.5
    level_repression: -0.01
    level_repression_limit: 0
    enchant:
      sharpness:
        1

#添加rpg游戏场地
game_field:
  #id
  field_1:
    #场地名称
    name: 测试1
    #场地长方形区域确定
    x_coordinates: [100,300] #x坐标
    z_coordinates: [200,300] #z坐标
    is_available: true #是否开放给玩家，如果不开放，在尝试进入时提示下面内容
    closed_message: 本区域暂未开放，换一个试试吧!
    allow_build_y: [0,0] #左闭右开区间，表示了哪个y坐标区域允许玩家建造

