name: BetterAttack
version: 1.0.0
author: Steve
main: org.steve.betterattack.Main
api-version: 1.16

commands:
  betterattack:
    usage: 命令格式错误，请使用/betterattack help
    permission: betterattack.use
    aliases:
      - ba
  betterattackadmin:
    usage: use /betterattackadmin help
    permission: betterattack.admin
    aliases:
      - baa

permissions:
  betterattack.*:
    children:
      betterattack.use: true
      betterattack.admin: true
  betterattack.use:
    default: true
  betterattack.admin:
    default: op