name: BetterAttack
version: 1.0.0
author: Steve
main: org.steve.betterattack.Main
api-version: 1.16

commands:
  betterattack:
    usage: 命令格式错误，请使用/betterattack help
    permission: BetterAttack.use

permissions:
  betterattack.*:
    description: 使用攻击强化的权限
    children:
      betterattack.use: true
  betterattack.use:
    default: true